CREATE TABLE languages (
    `id` mediumint unsigned NOT NULL AUTO_INCREMENT,  -- Auto-incremented primary key
    iso VARCHAR(64) NOT NULL,                      -- Short representation of language
    name VARCHAR(64) NOT NULL,                      -- Full name of the language
    PRIMARY KEY(id)                                  -- Primary key constraint on id column
)
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci   -- Set character set and collation
ENGINE = InnoDB;


INSERT INTO `languages` (`iso`, `name`) VALUES ('ab', 'Abkhazian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ace', 'Achinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ach', 'Acoli');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ada', 'Adangme');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ady', 'Adyghe');
INSERT INTO `languages` (`iso`, `name`) VALUES ('aa', 'Afar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('afh', 'Afrihili');
INSERT INTO `languages` (`iso`, `name`) VALUES ('af', 'Afrikaans');
INSERT INTO `languages` (`iso`, `name`) VALUES ('agq', 'Aghem');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ain', 'Ainu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ak', 'Akan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('akk', 'Akkadian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bss', 'Akoose');
INSERT INTO `languages` (`iso`, `name`) VALUES ('akz', 'Alabama');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sq', 'Albanian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ale', 'Aleut');
INSERT INTO `languages` (`iso`, `name`) VALUES ('arq', 'Algerian Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('am', 'Amarik');
INSERT INTO `languages` (`iso`, `name`) VALUES ('en_US', 'American English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ase', 'American Sign Language');
INSERT INTO `languages` (`iso`, `name`) VALUES ('egy', 'Ancient Egyptian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('grc', 'Ancient Greek');
INSERT INTO `languages` (`iso`, `name`) VALUES ('anp', 'Angika');
INSERT INTO `languages` (`iso`, `name`) VALUES ('njo', 'Ao Naga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ar', 'Arabik');
INSERT INTO `languages` (`iso`, `name`) VALUES ('an', 'Aragonese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('arc', 'Aramaic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('aro', 'Araona');
INSERT INTO `languages` (`iso`, `name`) VALUES ('arp', 'Arapaho');
INSERT INTO `languages` (`iso`, `name`) VALUES ('arw', 'Arawak');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hy', 'Armenian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rup', 'Aromanian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('frp', 'Arpitan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('as', 'Assamese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ast', 'Asturian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('asa', 'Asu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cch', 'Atsam');
INSERT INTO `languages` (`iso`, `name`) VALUES ('en_AU', 'Australian English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('de_AT', 'Austrian German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('av', 'Avaric');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ae', 'Avestan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('awa', 'Awadhi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ay', 'Aymara');
INSERT INTO `languages` (`iso`, `name`) VALUES ('az', 'Azerbaijani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bfq', 'Badaga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ksf', 'Bafia');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bfd', 'Bafut');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bqi', 'Bakhtiari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ban', 'Balinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bal', 'Baluchi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bm', 'Bambara');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bax', 'Bamun');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bjn', 'Banjar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bas', 'Basaa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ba', 'Bashkir');
INSERT INTO `languages` (`iso`, `name`) VALUES ('eu', 'Basque');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bbc', 'Batak Toba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bar', 'Bavarian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bej', 'Beja');
INSERT INTO `languages` (`iso`, `name`) VALUES ('be', 'Belarus kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bem', 'Bemba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bez', 'Bena');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bn', 'Bengali kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bew', 'Betawi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('my', 'Bɛɛmis kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bho', 'Bhojpuri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bik', 'Bikol');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bin', 'Bini');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bpy', 'Bishnupriya');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bi', 'Bislama');
INSERT INTO `languages` (`iso`, `name`) VALUES ('byn', 'Blin');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zbl', 'Blissymbols');
INSERT INTO `languages` (`iso`, `name`) VALUES ('brx', 'Bodo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('en', 'Borɔfo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bs', 'Bosnian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bg', 'Bɔlgeria kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('brh', 'Brahui');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bra', 'Braj');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pt_BR', 'Brazilian Portuguese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('br', 'Breton');
INSERT INTO `languages` (`iso`, `name`) VALUES ('en_GB', 'British English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bug', 'Buginese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bum', 'Bulu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bua', 'Buriat');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cad', 'Caddo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('frc', 'Cajun French');
INSERT INTO `languages` (`iso`, `name`) VALUES ('en_CA', 'Canadian English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fr_CA', 'Canadian French');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yue', 'Cantonese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cps', 'Capiznon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('car', 'Carib');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ca', 'Catalan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cay', 'Cayuga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ceb', 'Cebuano');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tzm', 'Central Atlas Tamazight');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dtp', 'Central Dusun');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ckb', 'Central Kurdish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('esu', 'Central Yupik');
INSERT INTO `languages` (`iso`, `name`) VALUES ('shu', 'Chadian Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chg', 'Chagatai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ch', 'Chamorro');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ce', 'Chechen');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chr', 'Cherokee');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chy', 'Cheyenne');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chb', 'Chibcha');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cgg', 'Chiga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('qug', 'Chimborazo Highland Quichua');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chn', 'Chinook Jargon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chp', 'Chipewyan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cho', 'Choctaw');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cu', 'Church Slavic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chk', 'Chuukese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cv', 'Chuvash');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nwc', 'Classical Newari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('syc', 'Classical Syriac');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ksh', 'Colognian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('swb', 'Comorian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('swc', 'Congo Swahili');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cop', 'Coptic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kw', 'Cornish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('co', 'Corsican');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cr', 'Cree');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mus', 'Creek');
INSERT INTO `languages` (`iso`, `name`) VALUES ('crh', 'Crimean Turkish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hr', 'Croatian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dak', 'Dakota');
INSERT INTO `languages` (`iso`, `name`) VALUES ('da', 'Danish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dar', 'Dargwa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dzg', 'Dazaga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('del', 'Delaware');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nl', 'Dɛɛkye');
INSERT INTO `languages` (`iso`, `name`) VALUES ('din', 'Dinka');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dv', 'Divehi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('doi', 'Dogri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dgr', 'Dogrib');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dua', 'Duala');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dyu', 'Dyula');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dz', 'Dzongkha');
INSERT INTO `languages` (`iso`, `name`) VALUES ('frs', 'Eastern Frisian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('efi', 'Efik');
INSERT INTO `languages` (`iso`, `name`) VALUES ('arz', 'Egyptian Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('eka', 'Ekajuk');
INSERT INTO `languages` (`iso`, `name`) VALUES ('elx', 'Elamite');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ebu', 'Embu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('egl', 'Emilian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('myv', 'Erzya');
INSERT INTO `languages` (`iso`, `name`) VALUES ('eo', 'Esperanto');
INSERT INTO `languages` (`iso`, `name`) VALUES ('et', 'Estonian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pt_PT', 'European Portuguese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('es_ES', 'European Spanish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ee', 'Ewe');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ewo', 'Ewondo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ext', 'Extremaduran');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fan', 'Fang');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fat', 'Fanti');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fo', 'Faroese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hif', 'Fiji Hindi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fj', 'Fijian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fil', 'Filipino');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fi', 'Finnish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nl_BE', 'Flemish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fon', 'Fon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gur', 'Frafra');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fr', 'Frɛnkye');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fur', 'Friulian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ff', 'Fulah');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gaa', 'Ga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gag', 'Gagauz');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gl', 'Galician');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gan', 'Gan Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lg', 'Ganda');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gay', 'Gayo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gba', 'Gbaya');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gez', 'Geez');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ka', 'Georgian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('aln', 'Gheg Albanian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bbj', 'Ghomala');
INSERT INTO `languages` (`iso`, `name`) VALUES ('glk', 'Gilaki');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gil', 'Gilbertese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gom', 'Goan Konkani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gon', 'Gondi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gor', 'Gorontalo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('got', 'Gothic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('grb', 'Grebo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('el', 'Greek kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gn', 'Guarani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gu', 'Gujarati');
INSERT INTO `languages` (`iso`, `name`) VALUES ('guz', 'Gusii');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gwi', 'Gwichʼin');
INSERT INTO `languages` (`iso`, `name`) VALUES ('de', 'Gyaaman');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jv', 'Gyabanis kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ja', 'Gyapan kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hai', 'Haida');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ht', 'Haitian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hak', 'Hakka Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hu', 'Hangri kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ha', 'Hausa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('haw', 'Hawaiian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('he', 'Hebrew');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hz', 'Herero');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hil', 'Hiligaynon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hi', 'Hindi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ho', 'Hiri Motu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hit', 'Hittite');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hmn', 'Hmong');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hup', 'Hupa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('iba', 'Iban');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ibb', 'Ibibio');
INSERT INTO `languages` (`iso`, `name`) VALUES ('is', 'Icelandic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('io', 'Ido');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ig', 'Igbo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ilo', 'Iloko');
INSERT INTO `languages` (`iso`, `name`) VALUES ('smn', 'Inari Sami');
INSERT INTO `languages` (`iso`, `name`) VALUES ('id', 'Indonihyia kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('izh', 'Ingrian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('inh', 'Ingush');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ia', 'Interlingua');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ie', 'Interlingue');
INSERT INTO `languages` (`iso`, `name`) VALUES ('iu', 'Inuktitut');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ik', 'Inupiaq');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ga', 'Irish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('it', 'Italy kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jam', 'Jamaican Creole English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kaj', 'Jju');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dyo', 'Jola-Fonyi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jrb', 'Judeo-Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jpr', 'Judeo-Persian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jut', 'Jutish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kbd', 'Kabardian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kea', 'Kabuverdianu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kab', 'Kabyle');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kac', 'Kachin');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kgp', 'Kaingang');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kkj', 'Kako');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kl', 'Kalaallisut');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kln', 'Kalenjin');
INSERT INTO `languages` (`iso`, `name`) VALUES ('xal', 'Kalmyk');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kam', 'Kamba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('km', 'Kambodia kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kbl', 'Kanembu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kn', 'Kannada');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kr', 'Kanuri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kaa', 'Kara-Kalpak');
INSERT INTO `languages` (`iso`, `name`) VALUES ('krc', 'Karachay-Balkar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('krl', 'Karelian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ks', 'Kashmiri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('csb', 'Kashubian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kaw', 'Kawi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kk', 'Kazakh');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ken', 'Kenyang');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kha', 'Khasi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kho', 'Khotanese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('khw', 'Khowar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ki', 'Kikuyu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kmb', 'Kimbundu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('krj', 'Kinaray-a');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kiu', 'Kirmanjki');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tlh', 'Klingon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bkm', 'Kom');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kv', 'Komi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('koi', 'Komi-Permyak');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kg', 'Kongo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kok', 'Konkani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ko', 'Korea kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kfo', 'Koro');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kos', 'Kosraean');
INSERT INTO `languages` (`iso`, `name`) VALUES ('avk', 'Kotava');
INSERT INTO `languages` (`iso`, `name`) VALUES ('khq', 'Koyra Chiini');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ses', 'Koyraboro Senni');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kpe', 'Kpelle');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kri', 'Krio');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kj', 'Kuanyama');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kum', 'Kumyk');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ku', 'Kurdish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kru', 'Kurukh');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kut', 'Kutenai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nmg', 'Kwasio');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zh', 'Kyaena kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cs', 'Kyɛk kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ky', 'Kyrgyz');
INSERT INTO `languages` (`iso`, `name`) VALUES ('quc', 'Kʼicheʼ');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lad', 'Ladino');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lah', 'Lahnda');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lkt', 'Lakota');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lam', 'Lamba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lag', 'Langi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lo', 'Lao');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ltg', 'Latgalian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('la', 'Latin');
INSERT INTO `languages` (`iso`, `name`) VALUES ('es_419', 'Latin American Spanish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lv', 'Latvian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lzz', 'Laz');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lez', 'Lezghian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lij', 'Ligurian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('li', 'Limburgish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ln', 'Lingala');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lfn', 'Lingua Franca Nova');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lzh', 'Literary Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lt', 'Lithuanian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('liv', 'Livonian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jbo', 'Lojban');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lmo', 'Lombard');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nds', 'Low German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sli', 'Lower Silesian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dsb', 'Lower Sorbian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('loz', 'Lozi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lu', 'Luba-Katanga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lua', 'Luba-Lulua');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lui', 'Luiseno');
INSERT INTO `languages` (`iso`, `name`) VALUES ('smj', 'Lule Sami');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lun', 'Lunda');
INSERT INTO `languages` (`iso`, `name`) VALUES ('luo', 'Luo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lb', 'Luxembourgish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('luy', 'Luyia');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mde', 'Maba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mk', 'Macedonian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jmc', 'Machame');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mad', 'Madurese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('maf', 'Mafa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mag', 'Magahi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vmf', 'Main-Franconian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mai', 'Maithili');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mak', 'Makasar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mgh', 'Makhuwa-Meetto');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kde', 'Makonde');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mg', 'Malagasy');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ms', 'Malay kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ml', 'Malayalam');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mt', 'Maltese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mnc', 'Manchu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mdr', 'Mandar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('man', 'Mandingo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mni', 'Manipuri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gv', 'Manx');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mi', 'Maori');
INSERT INTO `languages` (`iso`, `name`) VALUES ('arn', 'Mapuche');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mr', 'Marathi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('chm', 'Mari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mh', 'Marshallese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mwr', 'Marwari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mas', 'Masai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mzn', 'Mazanderani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('byv', 'Medumba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('men', 'Mende');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mwv', 'Mentawai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mer', 'Meru');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mgo', 'Metaʼ');
INSERT INTO `languages` (`iso`, `name`) VALUES ('es_MX', 'Mexican Spanish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mic', 'Micmac');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dum', 'Middle Dutch');
INSERT INTO `languages` (`iso`, `name`) VALUES ('enm', 'Middle English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('frm', 'Middle French');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gmh', 'Middle High German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mga', 'Middle Irish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nan', 'Min Nan Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('min', 'Minangkabau');
INSERT INTO `languages` (`iso`, `name`) VALUES ('xmf', 'Mingrelian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mwl', 'Mirandese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lus', 'Mizo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ar_001', 'Modern Standard Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('moh', 'Mohawk');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mdf', 'Moksha');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ro_MD', 'Moldavian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('lol', 'Mongo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mn', 'Mongolian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mfe', 'Morisyen');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ary', 'Moroccan Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mos', 'Mossi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mul', 'Multiple Languages');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mua', 'Mundang');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ttt', 'Muslim Tat');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mye', 'Myene');
INSERT INTO `languages` (`iso`, `name`) VALUES ('naq', 'Nama');
INSERT INTO `languages` (`iso`, `name`) VALUES ('na', 'Nauru');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nv', 'Navajo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ng', 'Ndonga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nap', 'Neapolitan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('new', 'Newari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ne', 'Nɛpal kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sba', 'Ngambay');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nnh', 'Ngiemboon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('jgo', 'Ngomba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yrl', 'Nheengatu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nia', 'Nias');
INSERT INTO `languages` (`iso`, `name`) VALUES ('niu', 'Niuean');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zxx', 'No linguistic content');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nog', 'Nogai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nd', 'North Ndebele');
INSERT INTO `languages` (`iso`, `name`) VALUES ('frr', 'Northern Frisian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('se', 'Northern Sami');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nso', 'Northern Sotho');
INSERT INTO `languages` (`iso`, `name`) VALUES ('no', 'Norwegian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nb', 'Norwegian Bokmål');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nn', 'Norwegian Nynorsk');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nov', 'Novial');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nus', 'Nuer');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nym', 'Nyamwezi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ny', 'Nyanja');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nyn', 'Nyankole');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tog', 'Nyasa Tonga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nyo', 'Nyoro');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nzi', 'Nzima');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nqo', 'NʼKo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('oc', 'Occitan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('oj', 'Ojibwa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ang', 'Old English');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fro', 'Old French');
INSERT INTO `languages` (`iso`, `name`) VALUES ('goh', 'Old High German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sga', 'Old Irish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('non', 'Old Norse');
INSERT INTO `languages` (`iso`, `name`) VALUES ('peo', 'Old Persian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pro', 'Old Provençal');
INSERT INTO `languages` (`iso`, `name`) VALUES ('or', 'Oriya');
INSERT INTO `languages` (`iso`, `name`) VALUES ('om', 'Oromo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('osa', 'Osage');
INSERT INTO `languages` (`iso`, `name`) VALUES ('os', 'Ossetic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ota', 'Ottoman Turkish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pal', 'Pahlavi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pfl', 'Palatine German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pau', 'Palauan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pi', 'Pali');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pam', 'Pampanga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pag', 'Pangasinan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pap', 'Papiamento');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ps', 'Pashto');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pdc', 'Pennsylvania German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fa', 'Pɛɛhyia kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('phn', 'Phoenician');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pcd', 'Picard');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pms', 'Piedmontese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pdt', 'Plautdietsch');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pon', 'Pohnpeian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pnt', 'Pontic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pl', 'Pɔland kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pt', 'Pɔɔtugal kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('prg', 'Prussian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('pa', 'Pungyabi kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('qu', 'Quechua');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ru', 'Rahyia kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('raj', 'Rajasthani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rap', 'Rapanui');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rar', 'Rarotongan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rw', 'Rewanda kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rif', 'Riffian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rgn', 'Romagnol');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rm', 'Romansh');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rom', 'Romany');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rof', 'Rombo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ro', 'Romenia kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('root', 'Root');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rtm', 'Rotuman');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rug', 'Roviana');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rn', 'Rundi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rue', 'Rusyn');
INSERT INTO `languages` (`iso`, `name`) VALUES ('rwk', 'Rwa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ssy', 'Saho');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sah', 'Sakha');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sam', 'Samaritan Aramaic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('saq', 'Samburu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sm', 'Samoan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sgs', 'Samogitian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sad', 'Sandawe');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sg', 'Sango');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sbp', 'Sangu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sa', 'Sanskrit');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sat', 'Santali');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sc', 'Sardinian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sas', 'Sasak');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sdc', 'Sassarese Sardinian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('stq', 'Saterland Frisian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('saz', 'Saurashtra');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sco', 'Scots');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gd', 'Scottish Gaelic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sly', 'Selayar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sel', 'Selkup');
INSERT INTO `languages` (`iso`, `name`) VALUES ('seh', 'Sena');
INSERT INTO `languages` (`iso`, `name`) VALUES ('see', 'Seneca');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sr', 'Serbian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sh', 'Serbo-Croatian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('srr', 'Serer');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sei', 'Seri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ksb', 'Shambala');
INSERT INTO `languages` (`iso`, `name`) VALUES ('shn', 'Shan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sn', 'Shona');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ii', 'Sichuan Yi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('scn', 'Sicilian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sid', 'Sidamo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bla', 'Siksika');
INSERT INTO `languages` (`iso`, `name`) VALUES ('szl', 'Silesian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zh_Hans', 'Simplified Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sd', 'Sindhi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('si', 'Sinhala');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sms', 'Skolt Sami');
INSERT INTO `languages` (`iso`, `name`) VALUES ('den', 'Slave');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sk', 'Slovak');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sl', 'Slovenian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('xog', 'Soga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sog', 'Sogdien');
INSERT INTO `languages` (`iso`, `name`) VALUES ('so', 'Somalia kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('snk', 'Soninke');
INSERT INTO `languages` (`iso`, `name`) VALUES ('azb', 'South Azerbaijani');
INSERT INTO `languages` (`iso`, `name`) VALUES ('nr', 'South Ndebele');
INSERT INTO `languages` (`iso`, `name`) VALUES ('alt', 'Southern Altai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sma', 'Southern Sami');
INSERT INTO `languages` (`iso`, `name`) VALUES ('st', 'Southern Sotho');
INSERT INTO `languages` (`iso`, `name`) VALUES ('es', 'Spain kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('srn', 'Sranan Tongo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zgh', 'Standard Moroccan Tamazight');
INSERT INTO `languages` (`iso`, `name`) VALUES ('suk', 'Sukuma');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sux', 'Sumerian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('su', 'Sundanese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sus', 'Susu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sw', 'Swahili');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ss', 'Swati');
INSERT INTO `languages` (`iso`, `name`) VALUES ('sv', 'Sweden kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fr_CH', 'Swiss French');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gsw', 'Swiss German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('de_CH', 'Swiss High German');
INSERT INTO `languages` (`iso`, `name`) VALUES ('syr', 'Syriac');
INSERT INTO `languages` (`iso`, `name`) VALUES ('shi', 'Tachelhit');
INSERT INTO `languages` (`iso`, `name`) VALUES ('th', 'Taeland kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tl', 'Tagalog');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ty', 'Tahitian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dav', 'Taita');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tg', 'Tajik');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tly', 'Talysh');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tmh', 'Tamashek');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ta', 'Tamil kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('trv', 'Taroko');
INSERT INTO `languages` (`iso`, `name`) VALUES ('twq', 'Tasawaq');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tt', 'Tatar');
INSERT INTO `languages` (`iso`, `name`) VALUES ('te', 'Telugu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ter', 'Tereno');
INSERT INTO `languages` (`iso`, `name`) VALUES ('teo', 'Teso');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tet', 'Tetum');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tr', 'Tɛɛki kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('bo', 'Tibetan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tig', 'Tigre');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ti', 'Tigrinya');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tem', 'Timne');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tiv', 'Tiv');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tli', 'Tlingit');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tpi', 'Tok Pisin');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tkl', 'Tokelau');
INSERT INTO `languages` (`iso`, `name`) VALUES ('to', 'Tongan');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fit', 'Tornedalen Finnish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zh_Hant', 'Traditional Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tkr', 'Tsakhur');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tsd', 'Tsakonian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tsi', 'Tsimshian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ts', 'Tsonga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tn', 'Tswana');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tcy', 'Tulu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tum', 'Tumbuka');
INSERT INTO `languages` (`iso`, `name`) VALUES ('aeb', 'Tunisian Arabic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tk', 'Turkmen');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tru', 'Turoyo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tvl', 'Tuvalu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tyv', 'Tuvinian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('tw', 'Twi');
INSERT INTO `languages` (`iso`, `name`) VALUES ('kcg', 'Tyap');
INSERT INTO `languages` (`iso`, `name`) VALUES ('udm', 'Udmurt');
INSERT INTO `languages` (`iso`, `name`) VALUES ('uga', 'Ugaritic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('uk', 'Ukren kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('umb', 'Umbundu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('und', 'Unknown Language');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hsb', 'Upper Sorbian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ur', 'Urdu kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ug', 'Uyghur');
INSERT INTO `languages` (`iso`, `name`) VALUES ('uz', 'Uzbek');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vai', 'Vai');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ve', 'Venda');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vec', 'Venetian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vep', 'Veps');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vi', 'Viɛtnam kasa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vo', 'Volapük');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vro', 'Võro');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vot', 'Votic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vun', 'Vunjo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('wa', 'Walloon');
INSERT INTO `languages` (`iso`, `name`) VALUES ('wae', 'Walser');
INSERT INTO `languages` (`iso`, `name`) VALUES ('war', 'Waray');
INSERT INTO `languages` (`iso`, `name`) VALUES ('wbp', 'Warlpiri');
INSERT INTO `languages` (`iso`, `name`) VALUES ('was', 'Washo');
INSERT INTO `languages` (`iso`, `name`) VALUES ('guc', 'Wayuu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('cy', 'Welsh');
INSERT INTO `languages` (`iso`, `name`) VALUES ('vls', 'West Flemish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('fy', 'Western Frisian');
INSERT INTO `languages` (`iso`, `name`) VALUES ('mrj', 'Western Mari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('wal', 'Wolaytta');
INSERT INTO `languages` (`iso`, `name`) VALUES ('wo', 'Wolof');
INSERT INTO `languages` (`iso`, `name`) VALUES ('wuu', 'Wu Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('xh', 'Xhosa');
INSERT INTO `languages` (`iso`, `name`) VALUES ('hsn', 'Xiang Chinese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yav', 'Yangben');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yao', 'Yao');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yap', 'Yapese');
INSERT INTO `languages` (`iso`, `name`) VALUES ('ybb', 'Yemba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yi', 'Yiddish');
INSERT INTO `languages` (`iso`, `name`) VALUES ('yo', 'Yoruba');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zap', 'Zapotec');
INSERT INTO `languages` (`iso`, `name`) VALUES ('dje', 'Zarma');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zza', 'Zaza');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zea', 'Zeelandic');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zen', 'Zenaga');
INSERT INTO `languages` (`iso`, `name`) VALUES ('za', 'Zhuang');
INSERT INTO `languages` (`iso`, `name`) VALUES ('gbz', 'Zoroastrian Dari');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zu', 'Zulu');
INSERT INTO `languages` (`iso`, `name`) VALUES ('zun', 'Zuni');
